---
title: "Code"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This page contains the complete code for the iris modeling example. For a detailed walkthrough, look at the other pages on this site. Note that this example uses a `workflow` object to create the final predictions, and thus the recipe and parsnip model are not prepped or fit independently. 

<br>

```{r, message = FALSE}
library(tidymodels)

# defining data_iris
data_iris <- bind_cols(all_of(iris), 
                       row = 1:nrow(iris))
```

```{r}
# RSample - generate data splits 
data_split <- initial_split(data_iris, prop = 3/4)

testing <- testing(data_split)
training <- training(data_split)
```

```{r}
# Recipes - define and apply preprocessing steps
iris_recipe <- recipe(Species ~ ., 
                      data = training) |>
  update_role(row, new_role = "ID") |>
  step_corr(all_numeric_predictors()) |>
  step_normalize(all_numeric_predictors()) |>
  step_rename(Row = row) 
```

```{r}
# Parsnip - create a model
rf <- rand_forest() |>
  set_mode("classification") |>
  set_args(trees = 500) |>
  set_engine("ranger")
```

```{r}
# Workflows - bundle recipe and model together and generate predictions
iris_wkf <- workflow() |>
  add_recipe(iris_recipe) |>
  add_model(rf) |>
  fit(training)

iris_preds <- iris_wkf |>
  augment(testing)
```

```{r}
# Yardstick - evaluate performance 
iris_preds |>
  roc_auc(Species, .pred_setosa:.pred_virginica)

iris_preds |>
  roc_curve(Species, .pred_setosa:.pred_virginica) |>
  autoplot()
```
